name: Bandit Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bandit:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bandit Python Security Scan
        uses: shundor/bandit-action@v2
        with:
          path: "."
          level: high
          confidence: high
          exit_zero: true
