name: AppScan CodeSweep

on:
  push:
    branches:
      - main  

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AppScan CodeSweep
        uses: ibm-security/AppScan-CodeSweep-GitHub-Action@main  # Use the default branch (main)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

